language: python
python:
- '2.7'
before_install:
- sudo apt-get update
- sudo apt-get install swig
install:
- DEB_HOST_MULTIARCH=x86_64-linux-gnu pip install -I --exists-action=w "git+git://anonscm.debian.org/collab-maint/m2crypto.git@debian/0.21.1-3#egg=M2Crypto"
- pip install --no-deps MySQL-Python==1.2.5 --use-mirrors
- pip install --find-links https://pyrepo.addons.mozilla.org/ peep
- peep install --no-deps -r requirements/test.txt --find-links https://pyrepo.addons.mozilla.org/
before_script:
- mysql -e 'create database solitude;'
after_script:
- flake8 . --exclude=./docs/conf.py
script: ./manage.py test --noinput -s
notifications:
  irc:
    channels:
    - irc.mozilla.org#amo-bots
    on_success: change
    on_failure: always
env:
  global:
    - secure: D4wiZ6EjJOgUf0AYdzSRDP153QEgv8g5jMMmwDYw2Jw7/vVqRddgqAYwAAxuB1d94Iux7BS2mFZzyYRcaOqwNkivu1aIp+pj8M7WCEXH4BxGEHPHM8gsIg6WstuWwO4JuINdwgslEs1D4/PYRq5oVI7O7zxvVzG7DJeQxP/79hw=
    - secure: gyV+8RH+6RQeoDbLFcSC9PL2nBYub1hIAZAJxBNwG5Z2Opah42m+b6k5otrFdsFVrQrmgA0D01s9u9Y11Ymf+ruagJa6ZIVP46aBxCRs5boa3QFIWB6l/RocWqJKZA6Z8XihSjeoQ+eXXTihyHUfl+HzltAqUr+WthO5eEGAiNc=
    - secure: Qjfu3W5kevg1zI2MlpIngoCt9mltQy7Ko0FrDEsXihSuXtAqsl6TcoJ5e0laYI0bnxWFohJwhWrH+R0+o5H2SnoIzb93u9xC/ytRQQ8zFFANWqflGmKPaxpVSt9hPhBOLVSusVwkPollpTdEr/ou77/qgU7p1CyPmVR6fDhsa88=
  matrix:
    - LIVE_TESTS=
    - LIVE_TESTS=live,!braintree
    - LIVE_TESTS=!live,braintree
matrix:
  allow_failures:
    - env: LIVE_TESTS=!live,braintree
